### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by ThiagoAlmeida0** [alex-custodio/Solidifly#1]
Basicamente criar uma tela de login 
 - A tela de login deve ter:
 
- [ ]  Botão de login com o google;

A data de entrega 02/07

**Comment by alex-custodio** [comment]
Ela precisa do campo de email e senha mesmo? achava q poderia ser mais fácil só com o botão do google

**Comment by ThiagoAlmeida0** [comment]
> Ela precisa do campo de email e senha mesmo? achava q poderia ser mais fácil só com o botão do google

Alterei para deixar só com o botão de login com google
